### 1. Numpy

In [2]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

In [ ]:
#checking numpy version

print(np.__version__)

In [ ]:
# ## 0-D Arrays

arr1=np.array(42)


# ## 1-D Array
arr2 = np.array([1,2,3,4,5])
# print(arr)

# ## 2-D Array

arr3 = np.array([[1,2,3],[4,5,6]])
# print(arr)

##3-D Array

arr4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
# print(arr)

## Check dimension of the ndarray

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

In [ ]:
## define ndim at time of declaration

arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print(f'Number of dimentsion: {arr.ndim}')

### 2. Array Indexing an Accessing Elements



In [ ]:
## 1-D Array

arr = np.array([1,2,3,4])

print(arr[1])

In [ ]:
## 2-D Array

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0,1]) # to print first row second column

print(arr[1,4]) # second row fifth element

### 3. Array Slicing


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) # [2 3 4 5]

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) # [7 8 9]

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4]) # [[2 3 4]
                        #[7 8 9]]

[[2 3 4]
 [7 8 9]]


### 4. Numpy Datatypes

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

In [ ]:
## Change data type with astype()

arr = np.array([1.1,2.1,3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

# [1 2 3]
# int32

### 5. Array View vs Copy

In [27]:
## view

arr = np.array([1,2,3,4])
x = arr.view()

arr[0] =10

print(x)
print(arr) ## view is changed as OG array changes

print(x.base)
print(arr.base)

[10  2  3  4]
[10  2  3  4]
[10  2  3  4]
None


In [28]:
## Copy

arr = np.array([1,2,3,4,5])
y = arr.copy()

arr[0] = 42

print(arr)
print(y)

print(arr.base)
print(y.base)

[42  2  3  4  5]
[1 2 3 4 5]
None
None


In [30]:
## reshape

arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr)

newarr = arr.reshape(5,2)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
## iteration

## np.nditer() , np.ndenumerate()

In [ ]:
## concatenate

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

## 

[1 2 3 4 5 6]


In [ ]:
## concatenate by axis

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) # concatenate along rows

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [42]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arrnew1 = np.stack((arr1, arr2), axis=1)
arrnew2 = np.concatenate((arr1,arr2))
print(arrnew1)
print('\n')
print(arrnew2)

[[1 4]
 [2 5]
 [3 6]]


[1 2 3 4 5 6]
